/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2022;

import org.junit.Test;

import aoc2022.helpers.Day;

import static org.junit.Assert.*;

import java.util.Optional;

public class AppTest {

    private static final Day dummyDay = x -> "";

    @Test
    public void nullFile() {
        assertEquals(Optional.empty(), dummyDay.apply(null));
    }

    @Test
    public void fileNotFound() {
        assertEquals(Optional.empty(), dummyDay.apply("This-file-does-not-exist"));
    }
}
